{
 "title": "PostgreSQL Performance Monitoring Dash",
 "tags": [ "postgres" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "database",
    "label": "database",
    "query": "SHOW TAG VALUES FROM \"postgresql.pg_stat_database\" WITH KEY=db  WHERE host=~/$server/"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY=cpu WHERE host=~/$server/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM disk WITH KEY=path  WHERE host=~/$server/"
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") /86400 AS \"days\" FROM \"autogen\".\"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/86400" ], "type": "math" },
       { "params": [ "days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "Database Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Current Connection Number",
   "type": "singlestat",
   "description": "Connection number indicates sum of active, idle and idle in transaction  number. It is not only active session. \n\nIf you want to check active session you can find an \"Active Sessions\" panel bellow. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "query": "SELECT last(\"number_of_conn\") AS \"active\" FROM \"postgresql.pg_stat_database_dtl\" WHERE (\"host\" =~ /^$server$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "number_of_conn" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "PG Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "pg_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PG Version" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "shared_buffers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8/1024" ], "type": "math" },
       { "params": [ "shared buffers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "maintenance_work_mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "max_parallel_workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "max_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max connections" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "work_mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Effective Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "effective_cache_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Wal Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "max_wal_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "postgresql.pg_check_replication_health",
     "select": [
      [
       { "params": [ "replay_lag" ], "type": "field" },
       { "params": [ "Replay Lag" ], "type": "alias" }
      ],
      [
       { "params": [ "replica_ip_in_hba" ], "type": "field" },
       { "params": [ "Replica Ip In Hba" ], "type": "alias" }
      ],
      [
       { "params": [ "usename" ], "type": "field" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "is_reachable" ], "type": "field" },
       { "params": [ "Is Reachable?" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_lag" ], "type": "field" },
       { "params": [ "Flush Lag" ], "type": "alias" }
      ],
      [
       { "params": [ "write_lag" ], "type": "field" },
       { "params": [ "Write Lag" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_lsn" ], "type": "field" },
       { "params": [ "Sent LSN" ], "type": "alias" }
      ],
      [
       { "params": [ "diff_in_bytes" ], "type": "field" },
       { "params": [ "Diff in Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Checkpoint Information",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_bgwriter",
     "query": "SELECT non_negative_difference(mean(\"checkpoints_req\")) AS \"Checkpoint Required\", non_negative_difference(mean(\"checkpoints_timed\")) AS \"Checkpoint Timed\", non_negative_difference(mean(\"checkpoints_timed\")) AS \"Checkpoint Timed\" FROM \"postgresql.pg_stat_bgwriter\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "checkpoints_req" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Checkpoint Required" ], "type": "alias" }
      ],
      [
       { "params": [ "checkpoints_timed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Checkpoint Timed" ], "type": "alias" }
      ],
      [
       { "params": [ "checkpoints_timed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Checkpoint Timed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "description": "(perfectly) Cache hit ratio should be > 90%",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "cache_hit_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "description": "Conflicts indicates number of queries canceled due to conflicts with recovery in this database. \n\nDeadlocks indicates number of deadlocks detected in this database\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "query": "SELECT non_negative_difference(mean(\"conflicts\")) AS \"conflicts\", non_negative_difference(mean(\"deadlocks\")) AS \"deadlocks\" FROM \"postgresql.pg_stat_database\" WHERE (\"host\" =~ /^$server$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "conflicts" ], "type": "alias" }
      ],
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "deadlocks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "fetched" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_returned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "returned" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "deleted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_inserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "inserted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_updated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "updated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Table Live/Dead Tuples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[$tag_datname] $col  [$tag_table_name]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.all_table_statistics",
     "select": [
      [
       { "params": [ "n_live_tup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "live tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "n_dead_tup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "dead tuple" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffers (BG Writer)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_bgwriter",
     "select": [
      [
       { "params": [ "buffers_backend" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "backend" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_checkpoint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "checkpoint" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_clean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "clean" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_backend_fsync" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "backend fsync" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "backend alloc" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Utilities",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "read block" ], "type": "alias" }
      ],
      [
       { "params": [ "blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "cached block" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "query": "SELECT mean(\"datsize_in_kb\") FROM \"postgresql.pg_stat_database_dtl\" WHERE (\"host\" =~ /^$server$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "datsize_in_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DB size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Data Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "select": [
      [
       { "params": [ "datsize_in_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "All Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "idle in transaction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle intransaction" ], "type": "alias" }
      ],
      [
       { "params": [ "all_sessions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "all sessions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_general_information",
     "select": [
      [
       { "params": [ "max_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max connections" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database_dtl",
     "select": [
      [
       { "params": [ "tps_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TPS Number" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "commit" ], "type": "alias" }
      ],
      [
       { "params": [ "xact_rollback" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "rollback" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Duration Of Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.block_detail",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Statement Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.block_detail",
     "query": "SELECT non_negative_difference(sum(\"calls\")) FROM \"postgresql.pg_stat_statements\" WHERE (\"host\" =~ /^$server$/ AND \"datname\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"datname\" fill(linear)",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.block_detail",
     "select": [
      [
       { "params": [ "shared_blks_dirtied" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Shared Blocks Dirtied" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Shared Blocks Catch Hit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.block_detail",
     "select": [
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Shared Blocks Dirtied" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "measurement": "postgresql.pg_stat_activity_active",
     "select": [
      [
       { "params": [ "usename" ], "type": "field" },
       { "params": [ "User Name" ], "type": "alias" }
      ],
      [
       { "params": [ "datname" ], "type": "field" },
       { "params": [ "Database" ], "type": "alias" }
      ],
      [
       { "params": [ "wait_event" ], "type": "field" },
       { "params": [ "Wait Event" ], "type": "alias" }
      ],
      [
       { "params": [ "client_addr" ], "type": "field" },
       { "params": [ "Client IP" ], "type": "alias" }
      ],
      [
       { "params": [ "wait_event_type" ], "type": "field" },
       { "params": [ "Wait Event Type" ], "type": "alias" }
      ],
      [
       { "params": [ "backend_type" ], "type": "field" },
       { "params": [ "Wait Event Type" ], "type": "alias" }
      ],
      [
       { "params": [ "pid" ], "type": "field" },
       { "params": [ "pid" ], "type": "alias" }
      ],
      [
       { "params": [ "qry_start" ], "type": "field" },
       { "params": [ "Query Start" ], "type": "alias" }
      ],
      [
       { "params": [ "xact_start" ], "type": "field" },
       { "params": [ "Trx Start" ], "type": "alias" }
      ],
      [
       { "params": [ "qry" ], "type": "field" },
       { "params": [ "Query" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Most 50 Time Consuming Queries",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "measurement": "postgresql.pg_most50_time_consuming_queries",
     "select": [
      [
       { "params": [ "datname" ], "type": "field" },
       { "params": [ "DB" ], "type": "alias" }
      ],
      [
       { "params": [ "username" ], "type": "field" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "queryid" ], "type": "field" },
       { "params": [ "QueryId" ], "type": "alias" }
      ],
      [
       { "params": [ "calls" ], "type": "field" },
       { "params": [ "Calls" ], "type": "alias" }
      ],
      [
       { "params": [ "mean_time" ], "type": "field" },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "min_time" ], "type": "field" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "max_time" ], "type": "field" },
       { "params": [ "Max " ], "type": "alias" }
      ],
      [
       { "params": [ "total_time" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "qry" ], "type": "field" },
       { "params": [ "Query" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Most 50 Called Queries",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "measurement": "postgresql.pg_most50_calls_queries",
     "select": [
      [
       { "params": [ "datname" ], "type": "field" },
       { "params": [ "DB" ], "type": "alias" }
      ],
      [
       { "params": [ "username" ], "type": "field" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "queryid" ], "type": "field" },
       { "params": [ "QueryId" ], "type": "alias" }
      ],
      [
       { "params": [ "calls" ], "type": "field" },
       { "params": [ "Calls" ], "type": "alias" }
      ],
      [
       { "params": [ "mean_time" ], "type": "field" },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "min_time" ], "type": "field" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "max_time" ], "type": "field" },
       { "params": [ "Max " ], "type": "alias" }
      ],
      [
       { "params": [ "total_time" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "qry" ], "type": "field" },
       { "params": [ "Query" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Most 50 Called Queries",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_qry",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "qry" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_most50_time_consuming_queries",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "All Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "schema_name" ], "type": "tag" },
      { "params": [ "table_name" ], "type": "tag" }
     ],
     "measurement": "postgresql.all_table_statistics",
     "select": [
      [
       { "params": [ "n_live_tup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Live Tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "n_dead_tup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Dead Tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "n_tup_del" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Deleted Tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "n_tup_upd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Updated Tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "n_tup_ins" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Inserted Tuple" ], "type": "alias" }
      ],
      [
       { "params": [ "idx_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Index Scan" ], "type": "alias" }
      ],
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Seq Scan" ], "type": "alias" }
      ],
      [
       { "params": [ "last_autovacuum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last Autovacuum" ], "type": "alias" }
      ],
      [
       { "params": [ "last_autoanalyze" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last Analyze" ], "type": "alias" }
      ],
      [
       { "params": [ "rel_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Relation Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "time", "operator": "<", "value": "now()-10s" }
     ]
    }
   ]
  },
  {
   "title": "Bloats",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "measurement": "postgresql.bloats",
     "query": "SELECT \"relname\" AS \"Relation Name\", \"bloat\" AS \"Bloat %\", \"wasted\" AS \"Wasted\", \"type\" AS \"Relation Type\", \"datname\" AS \"DB\" FROM \"postgresql.bloats\" WHERE (\"host\" =~ /^$server$/ AND \"datname\" =~ /^$database$/ AND \"time\" >= 'now()-20s') AND $timeFilter",
     "select": [
      [
       { "params": [ "datname" ], "type": "field" },
       { "params": [ "DB" ], "type": "alias" }
      ],
      [
       { "params": [ "relname" ], "type": "field" },
       { "params": [ "Relation Name" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" },
       { "params": [ "Relation Type" ], "type": "alias" }
      ],
      [
       { "params": [ "object_size" ], "type": "field" },
       { "params": [ "Relation Size" ], "type": "alias" }
      ],
      [
       { "params": [ "wasted" ], "type": "field" },
       { "params": [ "Wasted" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Size Of Temporary Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "temp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Size Of Temporary Files" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Number Of Temporary Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "postgresql.pg_stat_database",
     "select": [
      [
       { "params": [ "temp_files" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Number Of Temporary Files" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "User" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "System" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Steal" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "IO Wait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest Nice" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
       ]
      }
     ]
    },
    {
     "title": "Load Avareges",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Short" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Medium" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Long" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "User" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "System" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Steal" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "IO Wait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest Nice" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ],
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Cached" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Free" ], "type": "alias" }
        ],
        [
         { "params": [ "dirty" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Dirty" ], "type": "alias" }
        ],
        [
         { "params": [ "buffered" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Buffered" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "inodes_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "inodes_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"file-max\") as max FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"file-nr\") as opened FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CLOSED" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CLOSE_WAIT" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_closing" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CLOSING" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ESTABLISHED" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FIN_WAIT1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FIN_WAIT2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LAST_ACK" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SYN_RECV_ACK" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SYN_SENT" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TIME_WAIT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv4 errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "in discards",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "ip_indiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "ip_outdiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "ip_inhdrerrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "ip_outnoroutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "ip_inunknownprotos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Drops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}